export const USER_SIGN_IN = ['USER_SIGN_IN']
export const PRODUCTS = ['PRODUCTS']
export const SIGN_UP = ['SIGN_UP']
export const USER_INFO = ['USER_INFO']
export const PRODUCT_DETAIL = ['PRODUCT_DETAIL']
export const REVIEWS = ['REVIEWS']
